[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "deprecated>=1.3.1",
    "numpy>=2.3.5",
    "raylib==5.5.0.3",
]
